### ISSUE TITLE
AirDrop flares

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/production#3]
If you use 2 at the same time only ones drops comes

**Comment by 42MonthsAfter** [comment]
There are a couple different things at work here...

1. There are a certain number of airdrops that can be active at the same time. So say that limit is 3, there are 2 currently active in different parts of the map. You then pull 2 flares at the same time, only 1 would activate.

2. There might be something about how close they can be to each other... I'll investigate this one more.
